// src/app/layout.tsx
import { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './global.css';
import Header from '@/components/layout/Header';
import Footer from '@/components/layout/Footer';
import FloatingButton from '@/components/common/FloatingButton';
import FloatingSocialButtons from '@/components/common/FloatingSocialButtons';
import { ToastContainer } from 'react-toastify';
import ClientSessionProvider from '@/components/ClientSessionProvider';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Skinera',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/icon/icon.svg', type: 'image/svg+xml' },
      { url: '/icon/favicon.png', type: 'image/png' },
    ],
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <ClientSessionProvider>
          <Header />
          <main className="flex-grow">
            {children}
            <FloatingButton />
            <FloatingSocialButtons />
            <ToastContainer />
          </main>
          <Footer />
        </ClientSessionProvider>
      </body>
    </html>
  );
}
